### ISSUE TITLE
Error picking-up spine-generic/data-multi-subject manual labelling's

### ISSUE THREAD

**Issue by PaulBautin** [sct-pipeline/csa-atrophy#59]
For the moment label_if_does_not_exist() in process_data.sh does not pick-up the spine-generic/data-multi-subject manual labelling in derivatives. 

**To correct  this issue two options:**
- Do segmentation and labelling before reorientation and resampling (I am worried that segmentation will not be exactly be the same before and after reorientation and resampling)

- Change filename in function label_if_does_not_exist() after reorientation and resampling (there might be incoherence of trying to put a manual labelling on a resampled image)

What do you think @jcohenadad ?

**Comment by jcohenadad** [comment]
how about you resample the manual labeling (which is in the native space) into the space of the resampled data? you can do that in your script.

just make sure to use nearest neighbour because these are single voxels.

also, make sure the with NN, they do not disappear (we have some workarounds... but first, let's discuss the main strategy)

**Comment by PaulBautin** [comment]
That sounds like the best option. I guess i can use the same functions on the manual labelling files.
resampling function : `sct_resample -i ${file}.nii.gz -mm $interp -o ${file}_r.nii.gz`
reorienting function: `sct_image -i ${file}.nii.gz -setorient RPI -o ${file}_RPI.nii.gz`
