### ISSUE TITLE
Re-introduce padding in transformation

### ISSUE THREAD

**Issue by PaulBautin** [sct-pipeline/csa-atrophy#88]
Images with missing CSA reported in issue #86  all present segmentations that do not cover all vertebrae levels from C3 to C5. This issue only appeared once padding was removed. Therefore, my guess is that segmentation is not performed when cord approaches the image boundaries. I do not think this issue is causing outliers presented in issue #83, because as mentioned in issue #86 removing subjects with missing CSA mostly removes subjects with high COV and low error. 

@jcohenadad, What do yout think of re-integrate padding to see if it resolves this issue?

example:
Cropped and transformed image:
[sub-barcelona04_T1w_RPI_r_crop_r0.98_t1.zip](https://github.com/sct-pipeline/csa-atrophy/files/5435226/sub-barcelona04_T1w_RPI_r_crop_r0.98_t1.zip)
segmentation of ^ image
[sub-barcelona04_T1w_RPI_r_crop_r0.98_t1_seg.zip](https://github.com/sct-pipeline/csa-atrophy/files/5435227/sub-barcelona04_T1w_RPI_r_crop_r0.98_t1_seg.zip)

**Comment by jcohenadad** [comment]
I would definitely not reintroduce padding, because the problem here is not padding, but extreme transformation:
![image](https://user-images.githubusercontent.com/2482071/97192337-322c1500-177e-11eb-9080-95529746d911.png)

We can clearly see here that the spinal cord is cropped, causing a wrong estimation of the CSA, and wrongly contributing to a higher intra-subject COV. Adding padding will not solve this issue, it will only "hide" it. 

So, I would instead reconsider this hard-coded number "15", and increase it to something safer, like 30:
https://github.com/sct-pipeline/csa-atrophy/blob/61436baf54044309b4ce67fd8e4e2befe6f6b38a/process_data.sh#L72

**Comment by jcohenadad** [comment]
Illustration of the problem:
![image](https://user-images.githubusercontent.com/2482071/97228665-a16d2d80-17ad-11eb-80a6-349ae270bff6.png)

Suggestion of a solution:
![image](https://user-images.githubusercontent.com/2482071/97228763-c2ce1980-17ad-11eb-9b99-227ac8e76036.png)
